# Generated by Django 5.2.6 on 2025-09-29 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_training', '0003_alter_users_options_alter_users_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perevaladded',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perevals', to='job_training.perevallevel'),
        ),
    ]
