# Generated by Django 5.2.6 on 2025-10-06 16:50

import job_training.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_training', '0004_alter_perevaladded_level'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='users',
            managers=[
                ('objects', job_training.models.MyUserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='image',
            name='data',
        ),
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='users',
            name='fio',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(blank=True, max_length=150, unique=True),
        ),
    ]
