# Generated by Django 5.2.6 on 2025-10-01 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_training', '0004_alter_perevaladded_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='data',
        ),
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Изображение'),
        ),
    ]
